// categoryConstants.ts
export const CATEGORY_OPTIONS = [
    { category_id: 1, cat_long_name: "EQ - Large Cap", asset_class_id: 1 },
    { category_id: 2, cat_long_name: "EQ - Large & Midcap", asset_class_id: 1 },
    { category_id: 3, cat_long_name: "EQ - Flexicap / Multicap", asset_class_id: 1 },
    { category_id: 4, cat_long_name: "EQ - Focused", asset_class_id: 1 },
    { category_id: 5, cat_long_name: "EQ - Mid Cap", asset_class_id: 1 },
    { category_id: 7, cat_long_name: "EQ - Small Cap", asset_class_id: 1 },
    { category_id: 8, cat_long_name: "EQ - Thematic", asset_class_id: 1 },
    { category_id: 9, cat_long_name: "EQ - ELSS", asset_class_id: 1 },
    { category_id: 10, cat_long_name: "DEBT - Arbitrage", asset_class_id: 2 },
    { category_id: 11, cat_long_name: "DEBT - UST to Low Duration", asset_class_id: 2 },
    { category_id: 12, cat_long_name: "DEBT - Short Duration", asset_class_id: 2 },
    { category_id: 13, cat_long_name: "DEBT - Banking & PSU Debt", asset_class_id: 2 },
    { category_id: 14, cat_long_name: "DEBT - Corporate Bond", asset_class_id: 2 },
    { category_id: 15, cat_long_name: "DEBT - Medium Duration", asset_class_id: 2 },
    { category_id: 16, cat_long_name: "DEBT - Long Duration", asset_class_id: 2 },
    { category_id: 17, cat_long_name: "DEBT - Dynamic Duration", asset_class_id: 2 },
    { category_id: 18, cat_long_name: "DEBT - Gilt", asset_class_id: 2 },
    { category_id: 19, cat_long_name: "DEBT - Credit Risk", asset_class_id: 2 },
    { category_id: 20, cat_long_name: "DEBT - High Yield", asset_class_id: 2 },
    { category_id: 21, cat_long_name: "DEBT - Bank FDs", asset_class_id: 2 },
    { category_id: 22, cat_long_name: "DEBT - Bonds", asset_class_id: 2 },
    { category_id: 23, cat_long_name: "DEBT - PF/Govt Schemes", asset_class_id: 2 },
    { category_id: 24, cat_long_name: "DEBT - Debt ETF/FOF/Others", asset_class_id: 2 },
    { category_id: 25, cat_long_name: "DEBT - Asset Yielding", asset_class_id: 2 },
    { category_id: 26, cat_long_name: "DEBT - Liquid", asset_class_id: 2 },
    { category_id: 27, cat_long_name: "HYB - Conservative Hybrid", asset_class_id: 3 },
    { category_id: 28, cat_long_name: "HYB - Equity Savings", asset_class_id: 3 },
    { category_id: 29, cat_long_name: "HYB - Aggressive Hybrid", asset_class_id: 3 },
    { category_id: 30, cat_long_name: "HYB - Dynamic Asset Allocation", asset_class_id: 3 },
    { category_id: 31, cat_long_name: "HYB - Multi Asset", asset_class_id: 3 },
    { category_id: 32, cat_long_name: "HYB - Solution Oriented", asset_class_id: 3 },
    { category_id: 33, cat_long_name: "ALT - Gold", asset_class_id: 5 },
    { category_id: 34, cat_long_name: "ALT - Unlisted", asset_class_id: 5 },
    { category_id: 35, cat_long_name: "ALT - Absolute Long-Short", asset_class_id: 5 },
    { category_id: 36, cat_long_name: "ALT - Long-bias Long-Short", asset_class_id: 5 },
    { category_id: 37, cat_long_name: "RE - Physical RE", asset_class_id: 4 },
    { category_id: 38, cat_long_name: "RE - Real Estate Funds", asset_class_id: 4 },
    { category_id: 39, cat_long_name: "GL EQ - US Diversified", asset_class_id: 6 },
    { category_id: 40, cat_long_name: "GL EQ - US Tech", asset_class_id: 6 },
    { category_id: 41, cat_long_name: "GL EQ - Asia", asset_class_id: 6 },
    { category_id: 42, cat_long_name: "GL EQ - EM", asset_class_id: 6 },
    { category_id: 43, cat_long_name: "GL EQ - China", asset_class_id: 6 },
    { category_id: 44, cat_long_name: "GL EQ - Europe", asset_class_id: 6 },
    { category_id: 45, cat_long_name: "GL EQ - Global", asset_class_id: 6 },
    { category_id: 46, cat_long_name: "GL EQ - Global Thematic", asset_class_id: 6 },
    { category_id: 47, cat_long_name: "GL FI - US Debt", asset_class_id: 7 },
    { category_id: 48, cat_long_name: "GL FI - Ex-US Debt", asset_class_id: 7 },
    { category_id: 49, cat_long_name: "GL FI - REIT", asset_class_id: 7 },
    { category_id: 50, cat_long_name: "GL ALT - Global Unlisted", asset_class_id: 8 },
    { category_id: 51, cat_long_name: "GL ALT - Global Alternatives", asset_class_id: 8 },
    { category_id: 52, cat_long_name: "GL EQ - India", asset_class_id: 6 },
    { category_id: 53, cat_long_name: "DEBT - Income + Arbitrage", asset_class_id: 2 },
  ];

// Structure options for investment structures
export const STRUCTURE_OPTIONS = [
    { structure_id: 1, structure_name: "MF" },
    { structure_id: 2, structure_name: "PMS" },
    { structure_id: 3, structure_name: "AIF" },
    { structure_id: 4, structure_name: "Direct" },
    { structure_id: 5, structure_name: "Global" },
  ];
  
  // Helper function to get asset_class_id by category_id
export function getAssetClassIdByCategoryId(categoryId: number): number | null {
    const category = CATEGORY_OPTIONS.find(cat => cat.category_id === categoryId);
    return category?.asset_class_id || null;
  }