export type AccountOnboarding = {
    id: number,
    rel_group_id: number,
    status_client: string,
    status_internal: string,
    onboarding_title: string,
    get_customer_info: boolean,
    ops_check_info: boolean,
    forms_filled: boolean,
    sent_for_sig: boolean,
    form_recieved: boolean,
    form_processing: boolean,
    account_opened: boolean,
    funding_done: boolean,
    group_name: string,
    onboarding_type_name: string,
    process_client: string,
    process_ops: string,
};