export type AMC = {
    amc_name: string,
    id: number,
    slug: string,
    aum: number,
    structure: string,
    amc_rating: number,
    amc_pedigree_rating: number,
    amc_team_rating: number,
    amc_philosophy_rating: number,
    amc_size_rating: number,
    amc_pedigree: string,
    us_investor_tagging: string,
    team_pedigree: string,
    inv_team_risk: string,
    amc_maturity: string,
    inv_phil_name: string,
    inv_philosophy_followed: string,
    core_amc_team: string,
    amc_view: string,
    amc_pedigree_desc: string,
    team_pedigree_desc: string,
    inv_phil_desc: string,
    salient_points: string,
    amc_incorporation_dd: number,
    pms_license_number_dd: string,
    shareholding_structure_dd: string,
    team_changes_amc: string,
    other_biz_dd: string,
    legal_dd: string,
    fund_managers_mkt_mat: string,
    inv_team_amc: string,
    ops_team_amc: string,
    inv_committee_amc: string,
    ownership_alignment_amc: string,
    inv_philosophy_mkt_mat: string,
    portfolio_construction_mkt_mat: string,
    risk_management_mkt_mat: string,
    cash_management_mkt_mat: string,
    derivatives_mkt_mat: boolean,
    inv_process_mkt_mat: string,
    strategy_adherance_amc: string,
    active_schemes_mkt_mat: string,
    nav_chart_amc: string,
    cy_returns_amc: number,
    rolling_returns_mkt_mat: number,
    drawdown_history_amc: string,
    portfolio_composition_mkt_mat: string,
    qty_mktcap_composition_amc: string,
    portfolio_turnover_amc: number,
    section_allocation_amc: string,
    historic_calls_amc: string,
    black_swan_events_amc: string,
    firm_aum_sebi: number,
    strategy_aum_clients_sebi: number,
    capacity_contraints_amc: string,
    fee_mkt_mat: number,
    commission_mkt_mat: number,
    inv_comm_amc: string,
    disclosure_doc_mkt_mat: string,
    webinars_amc: string,
    custory_broker_mkt_mat: string,
    mailing_list_amc: boolean,
    disclosure_doc_last_check: Date,
    mkt_mat_last_check: Date,
    amc_diligence_last_check: Date,
    amc_fm_html: string,
    mkt_material_link: string,
    amc_body: string,
    // Optional SEO fields
    seo_title?: string | null;
    seo_description?: string | null;
    og_title?: string | null;
    og_description?: string | null;
    og_image?: string | null;
};