export type FinGoalsDetail = {
    goal_id: number,
    created_at: Date,
    group_id: number,
    goal_name: string,
    goal_description: string,
    goal_date: Date,
    exp_returns: number,
    inflation_rate: number,
    fv_goals: number,
    pv_goal: number,
    pv_inv: number,
    fv_inv: number,
    pending_amt: number,
    lumpsum_req: number,
    sip_req: number,
    yrs_to_goal: number,
    goal_ach: number,
};