
export type Investments = {
    investment_id: number,
    fund_name: string,
    asset_class_id: number,
    category_id: number,
    structure_id: number,
    group_id: number,
    investor_id: number,
    advisor_name: string,
    pur_amt: number,
    cur_amt: number,
    gain_loss: number,
    cagr: number,
    abs_ret: number,
    rms_fund_id: number,
    goal_id: number,
    source: string,
    amt_change: number,
    new_amt: number,
    fv_inv: number,
    recommendation: string,
    group_name: string,
    group_type: string,
    investor_name: string,
    goal_name: string,
    goal_description: string,
    goal_date: Date,
    inflation_rate: number,
    cat_name: string,
    cat_long_name: string,
    exp_return: number,
    fund_rms_name: string,
    fund_rating: number,
    one_yr: number,
    three_yr: number,
    five_yr: number,
    structure_name: string,
    asset_class_name: string,
    slug:string
};